def build(context):
    context(
        source = [
            "__init__.py",
            "distributed.py",
            "parallel.py",
            "serial.py",
            ],
        install_path = "${PYTHONDIR}/condor/managers",
        )

