def build(context):
    context(
        source = [
            "__init__.py",
            "admin.py",
            "labor.py",
            "work.py",
            "log.py",
            ],
        install_path = "${PYTHONDIR}/condor",
        )

