def build(context):
    context(
        source = [
            "__init__.py",
            "condor.py",
            "labor.py",
            "work.py",
            ],
        install_path = "${PYTHONDIR}/condor",
        )

