def build(context):
    context(
        source = [
            "__init__.py",
            "cache.py",
            "defaults.py",
            "log.py",
            "messages.py",
            "raw.py",
            "work.py",
            ],
        install_path = "${PYTHONDIR}/condor",
        )

    context.recurse("examples")
    context.recurse("managers")

